repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.13
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'
    hooks:
      - id: prettier
        types_or: [java, xml, javascript, ts, html, css, markdown]
        additional_dependencies:
          - prettier@2.8.8
          - "prettier-plugin-java@1.6.1"
          - "@prettier/plugin-xml@2.2.0"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: ['--strict']
        additional_dependencies: [
          pyomo
        ]
