[project]
name="food-powder-calculator"
description="An application for calculating the optimal food powder mix."
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "highspy",
    "maingopy",
    "pre-commit",
    "pyomo",
    "pytest",
    "ruff",
    "pyrefly"
]

[tool.ruff]
line-length = 80
indent-width = 4
target-version = "py313"

[tool.ruff.format]
docstring-code-format = true

[tool.mypy]
mypy_path = "src,stubs"

[tool.pyrefly]
search-path = ["src", "stubs"]
project-includes = ["src", "tests"]