[project]
name="food-powder-calculator"
description="An aplication for calculating the optimal food powder mix."
version = "0.1.0"
dependencies = [
    "highspy",
    "maingopy",
    "pre-commit",
    "pyomo",
    "pytest",
    "ruff",
]